# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "jakewendt-active_record_left_joins"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George 'Jake' Wendt"]
  s.date = "2013-12-03"
  s.description = "active_record_left_joins"
  s.email = "github@jakewendt.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/active_record_left_joins.rb",
    "lib/jakewendt-active_record_left_joins.rb"
  ]
  s.homepage = "http://github.com/jakewendt/active_record_left_joins"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "active_record_left_joins"
end

